### ISSUE TITLE
Consuming quoted values

### ISSUE THREAD

**Issue by dkandalov** [scopt/scopt#41] opened 2014-07-04 07:21 UTC
When consuming file name as a parameter it can possibly contain spaces. It seems that quoting file name or escaping space doesn't work (e.g. "/path/with space/" or /path/with\ space).

**Comment by onsails** [comment] 2015-10-18 02:51
:+1:

**Comment by cristipp** [comment] 2016-03-04 01:37
+1. I'd like to pass in argument lists like `-c 'qGroupNoun.DPRED(ISINTEGER) -> integers',qSlots`

**Comment by erfangc** [comment] 2016-08-23 17:42
👍

**Comment by Facsimiler** [comment] 2016-11-11 16:08
This seems to be a fairly major bug, since the space - even if quoted - acts as a command line delimiter. So it's impossible to pass an argument (such as a file path) that contains spaces to a program.

For example:

```
someutility "some/path/with spaces/somefile"
```

or

```
someutility some/path/with\ spaces/somefile
```

should be parsed as a single argument, but it's parsed as two, as though the spaces were not quoted:

```
someutility some/path/with spaces/somefile
```

If you only expect a single argument, this generates the error:

```
Error: Unknown argument 'spaces/somefile'
```

and, of course, there is no such file as "some/path/with".

UPDATE: I can confirm that the App trait's "args" member contains a single argument (a String array with a single member) that is passed to `OptionParser`'s `parse` method, so the command line escaping was honored by Bash (in this case). It appears that the `parse` method is breaking open its supplied arguments if they contain spaces.

**Comment by NathanC** [comment] 2017-01-04 17:46
+1 This seems to be a pretty major bug.

**Comment by cammydan** [comment] 2017-02-13 11:25
+1

**Comment by chernetsov** [comment] 2017-04-20 22:41
Wow, that's surprising how the library with almost 700 stars can have such a bug!

**Comment by graphex** [comment] 2019-05-30 21:14
I mean, I'm sure there are workarounds (%20 anyone?) but after 2 years and 4 releases, an ACK or WONTFIX reason from @eed3si9n would be appreciated!

**Comment by eed3si9n** [comment] 2019-05-30 21:22
I think it's a bug. I haven't really looked into the details since I haven't prioritized it, but I'd be happy to accept a PR or analysis on what's going on.

**Comment by avdv** [comment] 2019-08-26 14:46
Could someone provide a reproducer? With scopt 3.7.1 and
```scala
new scopt.OptionParser[Config]("sometool") {
                                                                                                                                             
  arg[String]("...")
    .unbounded()
    .optional()
    .action { (x, c) =>
       println(s"arg: $x")
       c
    }
   .text("path entries")
  help("help")
}
```
it works as expected for me:
```console
$ ./sometool abc\ def "asdf space 123"
arg: abc def
arg: asdf space 123
```

**Comment by eed3si9n** [comment] 2021-03-11 17:23
I'm going to close this since there are no reproducible steps. Feel free to resubmit a new issue if someone can come up with an example that should parse.

**Closed as completed by eed3si9n** 2021-03-11 17:23 UTC
Labels: bug
